### PR TITLE
Add self (@errikos) to team

### PR DESCRIPTION
**Pull request by errikos**
@ThiefMaster assigned this to me as task 0, so there you go. Added Developer entry and photo.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
I think the photo is missing there

**Comment by ThiefMaster** [comment]
Also, please use your CERN email address for commits - probably best to put it in your `~/.gitconfig` (ie use `git config --global`) so it applies to all repos.

**Comment by errikos** [comment]
Yeah forgot to add before commit. OK, will change the address as well.

**Comment by ThiefMaster** [comment]
Oh and general advice: Don't do PRs from master, always open a feature branch. Otherwise it's a mess when doing squash/rebase+merge. No need to reopen this one though.

**Comment by errikos** [comment]
Thanks! Will do, this seemed too trivial to branch...

**Comment by ThiefMaster** [comment]
the problem is that github always rewrites the commit even if it could fast-forward - so after doing such a merge using the UI here your master wouldn't be an ancestor of upstream's master anymore

**Pull request merged**
