### PR TITLE
Update copyright from –2019 to –2020

### PR DESCRIPTION
**Pull request by RaoOfPhysics**
Signed-off-by: Achintya Rao <achintya.rao@cern.ch>

### CODE REVIEW

**Comment by ThiefMaster** [comment]
thx!

**Comment by RaoOfPhysics** [comment]
Any time! (In fact, this is the third time. :P You guys need a reminder set for 31 December.)

**Comment by ThiefMaster** [comment]
we usually do it from the main repos, but tend to forget about the smaller ones until we touch them again ;)

probably a github actions cronjob could automatically update it every 1st of januar.. :D

**Comment by RaoOfPhysics** [comment]
Automation will render me irrelevant sooner than expected, @ThiefMaster. ;)

**Pull request merged**
